In [1]:
import pyphetools
import pandas as pd

# Extract the HPO seed terms separately for individuals and combine them into a cohort

In [2]:
hpo_parser = pyphetools.creation.HpoParser(hpo_json_file="../hp.json")

In [3]:
hpo_cr = hpo_parser.get_hpo_concept_recognizer()
# ontology = hpo_parser.get_ontology()

In [4]:
def get_hpo_terms_from_text(text_input_curator: str):
    """
    Extract and return HPO terms from an input text
    """
    hpo_terms = set()
    for line in text_input_curator.split("\n"):
        hpo_term_list = hpo_cr.parse_cell(line)
        for hpot in hpo_term_list:
            hpo_terms.add(hpot)
    return hpo_terms

In [5]:
class Individual_ET():

    def __init__(self, id, pmid, pmid_title, disease_id, disease_label,
                 hgnc_id, gene_symbol, transcript_id, allele_1, allele_2, variant_comment,
                 age_of_onset, age_at_last_encounter, deceased,
                 sex, hpo, text_input_curator, comment='na'):
        self.id = id # Higgins-Patient-1
        self.pmid = pmid # PMID:28289718
        self.pmid_title = pmid_title # Elucidation of MRAS-mediated Noonan syndrome with cardiac hypertrophy
        self.disease_id = disease_id # OMIM:618499
        self.disease_label = disease_label # Noonan syndrome-11
        self.hgnc_id = hgnc_id # HGNC:7227
        self.gene_symbol = gene_symbol # MRAS
        self.transcript_id = transcript_id # NM_001085049.3
        self.allele_1 = allele_1 # c.68G>T
        self.allele_2 = allele_2 # na
        self.variant_comment = variant_comment # Original notation NM_012219, c.68G>T
        self.age_of_onset = age_of_onset # P1Y8M0D
        self.age_at_last_encounter = age_at_last_encounter # P17Y
        self.deceased = deceased # yes|no|na
        self.sex = sex # M|F|O|U
        self.hpo = hpo # na
        self.text_input_curator = text_input_curator
        self.hpo_terms = get_hpo_terms_from_text(text_input_curator) # Set of ontolgy terms, e.g. (HP:0001714, "Ventricular hypertrophy")
        self.comment = None # na

    def get_pandas_df(self):
        # Set base columns
        columns = ["PMID", "title", "individual_id", "comment", "disease_id", "disease_label"]
        columns += ["HGNC_id", "gene_symbol", "transcript", "allele_1", "allele_2", "variant.comment"]
        columns += ["age_of_onset", "age_at_last_encounter", "deceased", "sex", "HPO"]
        # Initialize dataframe
        df = pd.DataFrame(columns=columns)
        df.loc[0] = [self.pmid, self.pmid_title, self.id, self.comment, self.disease_id, self.disease_label,
                     self.hgnc_id, self.gene_symbol, self.transcript_id, self.allele_1, self.allele_2, self.variant_comment,
                    self.age_of_onset, self.age_at_last_encounter, self.deceased,
                    self.sex, self.hpo]
        return df

In [14]:
individual_1 = Individual_ET(
    id="Higgins-Patient-1",
    pmid="PMID:28289718",
    pmid_title="Elucidation of MRAS-mediated Noonan syndrome with cardiac hypertrophy",
    disease_id="OMIM:618499",
    disease_label="Noonan syndrome-11",
    hgnc_id="HGNC:7227",
    gene_symbol="MRAS",
    transcript_id="NM_001085049.3",
    allele_1="c.68G>T",
    allele_2="na",
    variant_comment="Original notation NM_012219, c.68G>T",
    age_of_onset="P8Y",
    age_at_last_encounter="P17Y",
    deceased="na",
    sex="F",
    hpo="na",
    text_input_curator=
"""
biventricular hypertrophic cardiomyopathy. short stature, hypertelorism, and mildly posteriorly rotated ears.
low-set ears,
global developmental delay and cognitive disability.
biventricular cardiac hypertrophy in infancy following evaluation of a cardiac murmur.
In addition to cardiac hypertrophy, she presented with short stature and
facial dysmorphisms and with mildly posteriorly rotated ears (Figure 1B).
She also displayed a static pattern of globally delayed acquisition of developmental milestones and cognitive disability.
Clinical appearance of the patient at 17 years old, showing facial characteristics of Noonan syndrome, such as long facies and posteriorly rotated ears.
The echocardiogram shows left ventricular hypertrophy.
""",
    comment="na"
)
for hpo_term in individual_1.hpo_terms:
    print(hpo_term._id + ": " + hpo_term._label)
individual_1.get_pandas_df()

HP:0001263: Global developmental delay
HP:0000316: Hypertelorism
HP:0030148: Heart murmur
HP:0004322: Short stature
HP:0001712: Left ventricular hypertrophy
HP:0000369: Low-set ears
HP:0000276: Long face
HP:0000358: Posteriorly rotated ears
HP:0001639: Hypertrophic cardiomyopathy

,PMID,title,individual_id,comment,disease_id,disease_label,HGNC_id,gene_symbol,transcript,allele_1,allele_2,variant.comment,age_of_onset,age_at_last_encounter,deceased,sex,HPO
0,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Higgins-Patient-1,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,na,"Original notation NM_012219, c.68G>T",P8Y,P17Y,na,F,na

In [12]:
individual_2 = Individual_ET(
    id="Higgins-Patient-2",
    pmid="PMID:28289718",
    pmid_title="Elucidation of MRAS-mediated Noonan syndrome with cardiac hypertrophy",
    disease_id="OMIM:618499",
    disease_label="Noonan syndrome-11",
    hgnc_id="HGNC:7227",
    gene_symbol="MRAS",
    transcript_id="NM_001085049.3",
    allele_1="c.68G>T",
    allele_2="na",
    variant_comment="Original notation NM_012219, c.68G>T",
    age_of_onset="P8Y",
    age_at_last_encounter="P17Y",
    deceased="na",
    sex="F",
    hpo="na",
    text_input_curator=
"""
Hypertrophic cardiomyopathy
The second patient was a 6-year-old girl with low-set and posteriorly rotated ears,
mild pectus excavatum, wrinkled palms, hyperextensible small joints, ptosis, and hypotonia.
In addition, she had cardiac hypertrophy, pulmonary valve stenosis, and atrial septal defect.
She had moderate developmental delay                               
low set ears
and mildly posteriorly angulated ears,
very mild pectus excavatum, numerous wrinkles in her palms with slight redundancy of the soft tissue,
hyperextensibility of joints, and hypotonia.
apparent hypertelorism, mild ptosis, low-set,
posteriorly rotated ears and pointed chin    
""",
    comment="na"
)
for hpo_term in individual_2.hpo_terms:
    print(hpo_term._id + ": " + hpo_term._label)
individual_2.get_pandas_df()

HP:0001263: Global developmental delay
HP:0000316: Hypertelorism
HP:0001252: Hypotonia
HP:0001631: Atrial septal defect
HP:0001642: Pulmonic stenosis
HP:0000508: Ptosis
HP:0000307: Pointed chin
HP:0000767: Pectus excavatum
HP:0000369: Low-set ears
HP:0000358: Posteriorly rotated ears
HP:0001639: Hypertrophic cardiomyopathy

,PMID,title,individual_id,comment,disease_id,disease_label,HGNC_id,gene_symbol,transcript,allele_1,allele_2,variant.comment,age_of_onset,age_at_last_encounter,deceased,sex,HPO
0,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Higgins-Patient-2,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,na,"Original notation NM_012219, c.68G>T",P8Y,P17Y,na,F,na

In [13]:
individual_3 = Individual_ET(
    id="Suzuki-Patient-1",
    pmid="PMID:28289718",
    pmid_title="Elucidation of MRAS-mediated Noonan syndrome with cardiac hypertrophy",
    disease_id="OMIM:618499",
    disease_label="Noonan syndrome-11",
    hgnc_id="HGNC:7227",
    gene_symbol="MRAS",
    transcript_id="NM_001085049.3",
    allele_1="c.68G>T",
    allele_2="na",
    variant_comment="Original notation NM_012219, c.68G>T",
    age_of_onset="P8Y",
    age_at_last_encounter="P17Y",
    deceased="na",
    sex="F",
    hpo="na",
    text_input_curator=
"""
Suzuki et al. (2019) reported a 2-year-old boy with Noonan syndrome who was born by forceps delivery at 37 weeks to nonconsanguineous Japanese parents. He presented with cyanosis, tachycardia, and excessive sweating after crying, and was diagnosed with cardiac hypertrophy. His course was complicated by cardiac arrest, necessitating tracheostomy and long-term ventilation. At 4 months of age, he had feeding difficulty and was diagnosed with bilateral sensorineural hearing loss. At 32 months, he could sit alone for brief periods but could not stand. He did not use sign language. At 15 months, his height was -3.0 SD, but OFC was -1.5 SD, demonstrating relative macrocephaly. He had downslanting palpebral fissures, hypertelorism, depressed nasal bridge, bulbous nasal tip,
low-set ears with thick lobes, and full lips.                                   
Hypertrophic cardiomyopathy, Global developmental delay, Short stature   
""",
    comment="na"
)
for hpo_term in individual_3.hpo_terms:
    print(hpo_term._id + ": " + hpo_term._label)
individual_3.get_pandas_df()

HP:0001263: Global developmental delay
HP:0000316: Hypertelorism
HP:0001695: Cardiac arrest
HP:0000494: Downslanted palpebral fissures
HP:0005280: Depressed nasal bridge
HP:0000414: Bulbous nose
HP:0004322: Short stature
HP:0000369: Low-set ears
HP:0000975: Hyperhidrosis
HP:0012471: Thick vermilion border
HP:0011411: Forceps delivery
HP:0000961: Cyanosis
HP:0001649: Tachycardia
HP:0008619: Bilateral sensorineural hearing impairment
HP:0004482: Relative macrocephaly
HP:0001639: Hypertrophic cardiomyopathy

,PMID,title,individual_id,comment,disease_id,disease_label,HGNC_id,gene_symbol,transcript,allele_1,allele_2,variant.comment,age_of_onset,age_at_last_encounter,deceased,sex,HPO
0,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Suzuki-Patient-1,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,na,"Original notation NM_012219, c.68G>T",P8Y,P17Y,na,F,na

In [48]:
class Cohort_ET():

    def __init__(self, individuals: list):
        self.individuals = individuals

        # Join sets for the individuals
        self.hpo_set = set()
        for individual in individuals:
            self.hpo_set = self.hpo_set.union(individual.hpo_terms)
        print("[INFO] Found " + str(len(self.hpo_set)) + " HPO terms in total.")

        # Create table that shows for each of the joined HPO term if it is present in the three individuals
        hpo_table = []
        for hpo_term in self.hpo_set:
            hpo_row = []
            hpo_row.append(hpo_term._id)
            hpo_row.append(hpo_term._label)
            for individual in individuals:
                hpo_row.append(hpo_term in individual.hpo_terms)
            hpo_table.append(hpo_row)
        print(hpo_table)
        base_columns = ["HPO ID", "HPO Label"]
        individual_names = []
        for individual in individuals:
            individual_names.append(individual.id)
            #individual_names.append("Individual " + str(individual + 1))
        df = pd.DataFrame(hpo_table, columns=base_columns + individual_names)
        # Bring all rows with all columns TRUE to the top
        df = df.sort_values(by=individual_names, ascending=False)
        self.cohort_df = df

    def get_pandas_df(self):

        # Set base columns
        columns = ["PMID", "title", "individual_id", "comment", "disease_id", "disease_label"]
        columns += ["HGNC_id", "gene_symbol", "transcript", "allele_1", "allele_2", "variant.comment"]
        columns += ["age_of_onset", "age_at_last_encounter", "deceased", "sex", "HPO"]
        # Add columns for each HPO term
        for hpo_label in self.cohort_df["HPO Label"]:
            columns.append(hpo_label)
        df = pd.DataFrame(columns=columns)
        # Add first special row to the dataframe
        first_row = ['CURIE','str','str','optional','CURIE','str','CURIE','str','str','str','str','optional','age','age','yes/no/na','M:F:O:U','na']
        for hpo_id in self.cohort_df["HPO ID"]:
            first_row.append(hpo_id)
        df.loc[0] = first_row
        # Add the individuals to the dataframe
        for individual in self.individuals:
            individual_df = individual.get_pandas_df()
            # Add columns for each HPO term
            for hpo_term in self.hpo_set:
                individual_df[hpo_term._label] = hpo_term in individual.hpo_terms
            df = pd.concat([df, individual_df], ignore_index=True)
        # Replace logical TRUE with 'observed' and FALSE with 'na'
        df = df.replace(True, 'observed')
        df = df.replace(False, 'na')
        
        return df

In [49]:
cohort = Cohort_ET([individual_1, individual_2, individual_3])
cohort.cohort_df

[INFO] Found 26 HPO terms in total.
[['HP:0001263', 'Global developmental delay', True, True, True], ['HP:0000316', 'Hypertelorism', True, True, True], ['HP:0030148', 'Heart murmur', True, False, False], ['HP:0001631', 'Atrial septal defect', False, True, False], ['HP:0001642', 'Pulmonic stenosis', False, True, False], ['HP:0000508', 'Ptosis', False, True, False], ['HP:0000307', 'Pointed chin', False, True, False], ['HP:0000767', 'Pectus excavatum', False, True, False], ['HP:0000494', 'Downslanted palpebral fissures', False, False, True], ['HP:0000414', 'Bulbous nose', False, False, True], ['HP:0000975', 'Hyperhidrosis', False, False, True], ['HP:0001649', 'Tachycardia', False, False, True], ['HP:0004482', 'Relative macrocephaly', False, False, True], ['HP:0000276', 'Long face', True, False, False], ['HP:0001252', 'Hypotonia', False, True, False], ['HP:0001695', 'Cardiac arrest', False, False, True], ['HP:0005280', 'Depressed nasal bridge', False, False, True], ['HP:0004322', 'Short stature', True, False, True], ['HP:0001712', 'Left ventricular hypertrophy', True, False, False], ['HP:0000369', 'Low-set ears', True, True, True], ['HP:0012471', 'Thick vermilion border', False, False, True], ['HP:0011411', 'Forceps delivery', False, False, True], ['HP:0000961', 'Cyanosis', False, False, True], ['HP:0008619', 'Bilateral sensorineural hearing impairment', False, False, True], ['HP:0000358', 'Posteriorly rotated ears', True, True, False], ['HP:0001639', 'Hypertrophic cardiomyopathy', True, True, True]]

,HPO ID,HPO Label,Higgins-Patient-1,Higgins-Patient-2,Suzuki-Patient-1
0,HP:0001263,Global developmental delay,True,True,True
1,HP:0000316,Hypertelorism,True,True,True
19,HP:0000369,Low-set ears,True,True,True
25,HP:0001639,Hypertrophic cardiomyopathy,True,True,True
24,HP:0000358,Posteriorly rotated ears,True,True,False
17,HP:0004322,Short stature,True,False,True
2,HP:0030148,Heart murmur,True,False,False
13,HP:0000276,Long face,True,False,False
18,HP:0001712,Left ventricular hypertrophy,True,False,False
3,HP:0001631,Atrial septal defect,False,True,False
4,HP:0001642,Pulmonic stenosis,False,True,False
5,HP:0000508,Ptosis,False,True,False
6,HP:0000307,Pointed chin,False,True,False
7,HP:0000767,Pectus excavatum,False,True,False
14,HP:0001252,Hypotonia,False,True,False
8,HP:0000494,Downslanted palpebral fissures,False,False,True
9,HP:0000414,Bulbous nose,False,False,True
10,HP:0000975,Hyperhidrosis,False,False,True
11,HP:0001649,Tachycardia,False,False,True
12,HP:0004482,Relative macrocephaly,False,False,True
15,HP:0001695,Cardiac arrest,False,False,True
16,HP:0005280,Depressed nasal bridge,False,False,True
20,HP:0012471,Thick vermilion border,False,False,True
21,HP:0011411,Forceps delivery,False,False,True
22,HP:0000961,Cyanosis,False,False,True
23,HP:0008619,Bilateral sensorineural hearing impairment,False,False,True

In [50]:
cohort.get_pandas_df()

,PMID,title,individual_id,comment,disease_id,disease_label,HGNC_id,gene_symbol,transcript,allele_1,...,Bulbous nose,Hyperhidrosis,Tachycardia,Relative macrocephaly,Cardiac arrest,Depressed nasal bridge,Thick vermilion border,Forceps delivery,Cyanosis,Bilateral sensorineural hearing impairment
0,CURIE,str,str,optional,CURIE,str,CURIE,str,str,str,...,HP:0000414,HP:0000975,HP:0001649,HP:0004482,HP:0001695,HP:0005280,HP:0012471,HP:0011411,HP:0000961,HP:0008619
1,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Higgins-Patient-1,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,...,na,na,na,na,na,na,na,na,na,na
2,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Higgins-Patient-2,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,...,na,na,na,na,na,na,na,na,na,na
3,PMID:28289718,Elucidation of MRAS-mediated Noonan syndrome w...,Suzuki-Patient-1,None,OMIM:618499,Noonan syndrome-11,HGNC:7227,MRAS,NM_001085049.3,c.68G>T,...,observed,observed,observed,observed,observed,observed,observed,observed,observed,observed

In [56]:
print(cohort.get_pandas_df()['Global developmental delay'])
print(cohort.get_pandas_df()['Hypertelorism'])
print(cohort.get_pandas_df()['Low-set ears'])
print(cohort.get_pandas_df()['Hypertrophic cardiomyopathy'])
print(cohort.get_pandas_df()['Posteriorly rotated ears'])
print(cohort.get_pandas_df()['Short stature'])

0    HP:0001263
1      observed
2      observed
3      observed
Name: Global developmental delay, dtype: object
0    HP:0000316
1      observed
2      observed
3      observed
Name: Hypertelorism, dtype: object
0    HP:0000369
1      observed
2      observed
3      observed
Name: Low-set ears, dtype: object
0    HP:0001639
1      observed
2      observed
3      observed
Name: Hypertrophic cardiomyopathy, dtype: object
0    HP:0000358
1      observed
2      observed
3            na
Name: Posteriorly rotated ears, dtype: object
0    HP:0004322
1      observed
2            na
3      observed
Name: Short stature, dtype: object